### ISSUE TITLE
a missing file

### ISSUE THREAD

**Issue by gsh150801** [Ellenzzn/ChatMol#1]
Things go well until we run the getM2T.py:  
![image](https://github.com/Ellenzzn/ChatMol/assets/33688592/a05ff798-b087-44db-8af2-a692fd7f6ed5)  
 Traceback (most recent call last):  
  File "/share1-100G/shguan/projs/chat/ChatMol-main/predata/getM2T.py", line 41, in <module>  
    namedic = pickle.load(open('allcid2name.pkl', 'rb'))  
FileNotFoundError: [Errno 2] No such file or directory:   
It seems that the author miss to upload this file,'allcid2name.pkl'

**Comment by gsh150801** [comment]
@Ellenzzn

**Comment by Ellenzzn** [comment]
Thanks for raising this question. The original file is too large, and the necessary part has been extracted and uploaded as 'cid2name.pkl'.
